universe   = vanilla
initialdir = /home/gtirpitz/AI4ExoMars

executable = stage1_1ep.sh

output = job_outputs/stage1_training/stage1_1ep.$(Cluster).$(Process).out
error  = job_outputs/stage1_training/stage1_1ep.$(Cluster).$(Process).err
log    = job_outputs/stage1_training/stage1_1ep.$(Cluster).log

request_cpus   = 4
request_memory = 24576
request_gpus   = 1
min_gpu_mem_mb = 36000
requirements   = (TARGET.CUDAGlobalMemoryMb >= $(min_gpu_mem_mb))

getenv = True

+JobBatchName = "ai4exomars-stage1-1ep-bs128"

MaxTime = 43200  

periodic_hold = (JobStatus == 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))
periodic_hold_reason = "Job runtime exceeded MaxTime"

queue 1
